name = "testdrive_util"
version = "0.1.0"
license = "MIT"
author = "Tomohiro Degawa"
maintainer = "@degawa/testdrive_util"
copyright = "Copyright 2022, Tomohiro Degawa"

[build]
auto-tests = true
auto-examples = true

[install]
library = true

[dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive"}
