name = "testdrive_util"
version = "0.3.0"
license = "MIT"
author = "Tomohiro Degawa"
maintainer = "@degawa/testdrive_util"
copyright = "Copyright 2022-2023, Tomohiro Degawa"

[build]
auto-tests = true
auto-examples = true

[install]
library = true

[preprocess]
[preprocess.cpp]

[dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive"}
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
